### ISSUE TITLE
Clarification regarding the mappers(ICIJ & Dow Jones)

### ISSUE THREAD

**Issue by SaravananKalimuthu21** [Senzing/mapper-dowjones#12]
Jeff, 

We are in a need of clarification for the following few queries.

#1. Do you have any query statement to check how many records have been resolved/changed/created against a datasource(ICIJ or DOWJONES) in the postgres database?

#2. How to differentiate Aircraft People Entity and Vessel types in the mapper data? 

#3. Do you have these DJ Heirarcy information added into the Dow Jones Mappers?
![PEP DJRC Heirarchy](https://user-images.githubusercontent.com/48215082/77100317-74001a80-6a3b-11ea-8e11-f8e07fda62dc.png)

Thanks.

**Comment by jbutcher21** [comment]
Hi Saravanan,

On #1 see ... https://senzing.zendesk.com/hc/en-us/articles/360008922593-Interpreting-getSummaryData-Responses

On #2 ...  I am looking into this early next week. It will take a bit of work to reclassify the entity based on the description3 field, but we will see.

On #3 ... They are all under the description1 tag.  Will rename it to descriptions for next update.
![image](https://user-images.githubusercontent.com/22121925/77203494-c11cd480-6aad-11ea-85c6-a52e688e8753.png)

**Comment by SaravananKalimuthu21** [comment]
Hi Jeff,

Did you get a chance to take look at this?

#2. How to differentiate Aircraft People Entity and Vessel types in the mapper data?

Thanks.

**Comment by jbutcher21** [comment]
Hi Saravanan,

Looking at this today.   Looks like I should be able to change the record_type attribute to “AIRCRAFT” or “VESSEL”.   Possibly even create new fields for callsign, imo number, etc.   But can you tell me more of what you want to do with these records?   For instance, …

  *   do you just want the record_type so you know what icon to place on the graph?
  *   Do you need to be able to search by call sign or imo number, etc?
  *   Other?

Jeff Butcher
Senzing, Chief Architect
jbutcher@senzing.com<mailto:jbutcher@senzing.com>
(702) 205-8424

Follow Senzing on Website<http://www.senzing.com/> | Twitter<https://twitter.com/senzing> | LinkedIn<https://www.linkedin.com/company/senzing-inc/> | Facebook<https://www.facebook.com/senzinginc/>
If you are not an intended recipient of confidential and privileged information in this email, please delete it, notify us immediately at postmaster@senzing.com<mailto:postmaster@senzing.com>, and do not use or disseminate such information.

**Comment by SaravananKalimuthu21** [comment]
Yes, we need to fix icons according to the record_type.

We have different icons for each types(AIRCRAFT, VESSEL, SHIP etc) to be visualized in the graph.

**Comment by jbutcher21** [comment]
Have included support for these in the the latest release.  Also sent you email.
There are two new entity types: VESSEL and AIRCRAFT  (ships are vessels)
There are 4 new identifier features you can search for: IMO_NUMBER, MMSI_NUMBER for vessels; AIRCRAFT_MSN_NUMBER, AIRCRAFT_TAIL_NUMBER for aircraft.

**Comment by SaravananKalimuthu21** [comment]
Yeah Jeff, 

We received those. 

Thank you so much.
