### ISSUE TITLE
Need clarification on Dow Jones and ICIJ relationship data information.

### ISSUE THREAD

**Issue by SaravananKalimuthu21** [Senzing/mapper-dowjones#13]
Jeff, 

We have ICIJ and Dow Jones data in our database. It seems to have relationships for 1st level and 2level relationships.
 
Do we have 3rd level or 4th level relationship information?

If we have such, the 3rd or 4th level relationship attribute affect resolution?

Thanks.

**Comment by jbutcher21** [comment]
See these api calls ...
![image](https://user-images.githubusercontent.com/22121925/77800297-b628ed80-7033-11ea-8752-d25b6984d72f.png)

As far as using relationships to help resolution ... we have a group_association set of features that help resolve records between Dow Jones and IJIC.  Sometimes all these data sources have is a name and who they are affiliated with.   Of course this is just first level relationships being used for resolution.  But you could use the group associations for anything.

**Comment by jbutcher21** [comment]
Hi Saravan, was wondering if I could close this issue.   Did this answer your question?

**Comment by SaravananKalimuthu21** [comment]
Yes Jeff,

We are reading this. But unfortunately our server gets some crashes. We couldn't play around with it.

If you don't mind can we have a screen share once our server is fixed?

Thanks.

**Comment by jbutcher21** [comment]
Certainly!   Let me know when you are ready.

Jeff Butcher
Senzing, Chief Architect
jbutcher@senzing.com<mailto:jbutcher@senzing.com>
(702) 205-8424

Follow Senzing on Website<http://www.senzing.com/> | Twitter<https://twitter.com/senzing> | LinkedIn<https://www.linkedin.com/company/senzing-inc/> | Facebook<https://www.facebook.com/senzinginc/>
If you are not an intended recipient of confidential and privileged information in this email, please delete it, notify us immediately at postmaster@senzing.com<mailto:postmaster@senzing.com>, and do not use or disseminate such information.

**Comment by SaravananKalimuthu21** [comment]
Jeff,

We need a clarification on which file to be downloaded from dow jones site to upload the data in our db?

We have downloaded this file pfa2_202003312200_f.zip. Is this a recently updated file?

--------------------------------

Regarding 3rd level or 4th level relationship information,

Can we have a call with you? then we can able to know what kind of things we need to do.

Thanks.

**Comment by jbutcher21** [comment]
Hi Saravanan,

Yes, on the last day of each month dow jones makes  the _f (full file) for that month.  It is the one to load.  Make sure you pull the lastest mapping code withj vessels and aircraft support from here https://github.com/Senzing/mapper-dowjones.

Please give me a few meeting times to choose from.   I forgot what time zone you are in.   I am on pacific time.   Later in the day is better than earlier for me!

Jeff Butcher
Senzing, Chief Architect
jbutcher@senzing.com<mailto:jbutcher@senzing.com>
(702) 205-8424

Follow Senzing on Website<http://www.senzing.com/> | Twitter<https://twitter.com/senzing> | LinkedIn<https://www.linkedin.com/company/senzing-inc/> | Facebook<https://www.facebook.com/senzinginc/>
If you are not an intended recipient of confidential and privileged information in this email, please delete it, notify us immediately at postmaster@senzing.com<mailto:postmaster@senzing.com>, and do not use or disseminate such information.

**Comment by SaravananKalimuthu21** [comment]
Yes, we did download the latest mappers. 

--------------------------------------------------

I am in IST, Jeff.

Will these times work for you?

6PM IST or 7PM IST or 10PM IST.

**Comment by SaravananKalimuthu21** [comment]
Jeff,

We did upload these files also (dj-aircraft.json and dj-vessels.json).

What does this file do? **DJRC_HRF_XML_201903012359_F.xml** (Ref: https://github.com/Senzing/mapper-dowjones)
![otherfile](https://user-images.githubusercontent.com/48215082/78320439-10bbcf80-7587-11ea-9ae6-3c777dd53b90.png)

We didn't see these sort of files in the dowjones website.

Should we also upload this file?

**Comment by jbutcher21** [comment]
I wouldn’t bother with the HRF file unless directed to by Consilienz.

So I think you are 12.5 hours ahead of me.  So the 10pm isn’t would be good for me.   Pleas send a meeting with n ire and I will attend.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by SaravananKalimuthu21** [comment]
Okay.

Let me share the meeting link scheduled for 10PM IST. Please join if you can or else we can re-schedule.

**Comment by SaravananKalimuthu21** [comment]
Jeff,

We couldn't resolve the 3rd level and 4th level information by using the maxDegrees and buildOut params. We need someone else' help to get this done. 

-----------------

One more thing, why all the attributes under the relatedEntities are empty? 
![relatedEntities](https://user-images.githubusercontent.com/48215082/78670186-0426d680-78fb-11ea-97d9-b939f17b3018.png)


Did the mapper file needs to be modified to resolve this?

We need the marked attributes to be filled with the information as like as in the resolvedEntity.

Can you add the information into the relatedEntites as well?

Thanks.

**Comment by jbutcher21** [comment]
Hi Saravanan, 

I am going to close issue here as it has more to do with the engine than this mapper.  You will be notified
