### ISSUE TITLE
Suggested Change

### ISSUE THREAD

**Issue by KevinPowell2** [Senzing/mapper-dowjones#22]
Hey Jeff, 
Since we are replicating our data outside of the Senzing RDS, we wanted to modify the Record_ID field so as to avoid purely numeric fields getting confused from other sources (we added a 'DJ' in front of DJ profile ID #). After that we found that the the mapper was no longer writing relationship fields: (e.g. {"REL_POINTER_DOMAIN": "DJ_ID", "REL_POINTER_KEY": "10013314", "REL_POINTER_ROLE": "Asset"}) 
Found the issue in ln 622 of the dj_mapper.py script.  The code was trying to cross reference the Record_ID against relationships array, which no longer matched up.
SUGGESTED FIX:
dj_mapper.py(ln 622) -> thisId = jsonData['DJ_PROFILE_ID']

That data is duplicated, and this way you have the freedom to use whatever Record_ID you prefer.  Haven't found any other areas where this is an issue.

-Kevin from Redhorse

**Comment by docktermj** [comment]
@jbutcher21 - A mention so @jbutcher21 gets email.  :smile:

**Comment by jbutcher21** [comment]
Thanks Kevin.  That is indeed a good change and I will implement it today!
